from __future__ import annotations

from typing import Iterable


BLOCK_START = "# audioknob-gui rtirq begin"
BLOCK_END = "# audioknob-gui rtirq end"
BLOCK_HEADER = "# Generated by audioknob-gui. Do not edit."


def _dedupe(items: Iterable[str]) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for item in items:
        if item in seen:
            continue
        seen.add(item)
        out.append(item)
    return out


def normalize_rtirq_list(value: object) -> list[str]:
    if value is None:
        return []
    if isinstance(value, (list, tuple)):
        tokens: list[str] = []
        for item in value:
            if item is None:
                continue
            raw = str(item).replace(",", " ")
            tokens.extend(t for t in raw.split() if t)
        return _dedupe(tokens)
    raw = str(value).replace(",", " ")
    return _dedupe([t for t in raw.split() if t])


def _format_rtirq_list(items: list[str]) -> str:
    return " ".join(items)


def build_rtirq_block_lines(
    *,
    name_list: list[str],
    high_list: list[str],
    prio_high: int,
    prio_decr: int,
) -> list[str]:
    return [
        BLOCK_START,
        BLOCK_HEADER,
        f'RTIRQ_NAME_LIST="{_format_rtirq_list(name_list)}"',
        f'RTIRQ_HIGH_LIST="{_format_rtirq_list(high_list)}"',
        f"RTIRQ_PRIO_HIGH={prio_high}",
        f"RTIRQ_PRIO_DECR={prio_decr}",
        BLOCK_END,
    ]


def _strip_rtirq_block_lines(lines: list[str]) -> list[str]:
    out: list[str] = []
    in_block = False
    for line in lines:
        if line.strip() == BLOCK_START:
            in_block = True
            continue
        if in_block:
            if line.strip() == BLOCK_END:
                in_block = False
            continue
        out.append(line)
    return out


def strip_rtirq_block(text: str) -> str:
    lines = text.splitlines()
    stripped = _strip_rtirq_block_lines(lines)
    if not stripped:
        return ""
    return "\n".join(stripped).rstrip("\n") + "\n"


def apply_rtirq_block(
    text: str,
    *,
    name_list: list[str],
    high_list: list[str],
    prio_high: int,
    prio_decr: int,
) -> str:
    base = strip_rtirq_block(text)
    base_lines = base.splitlines()
    if base_lines and base_lines[-1].strip() != "":
        base_lines.append("")
    block_lines = build_rtirq_block_lines(
        name_list=name_list,
        high_list=high_list,
        prio_high=prio_high,
        prio_decr=prio_decr,
    )
    base_lines.extend(block_lines)
    return "\n".join(base_lines).rstrip("\n") + "\n"


def rtirq_block_present(
    text: str,
    *,
    name_list: list[str],
    high_list: list[str],
    prio_high: int,
    prio_decr: int,
) -> bool:
    block = "\n".join(
        build_rtirq_block_lines(
            name_list=name_list,
            high_list=high_list,
            prio_high=prio_high,
            prio_decr=prio_decr,
        )
    )
    return block in text
